name: calculation_game
description: calculation_game

 pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  font_awesome_flutter: ^9.2.0
  fraction: ^3.1.0
  math_parser: ^1.0.0
  shared_preferences: ^2.0.9
  google_mobile_ads: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSerifKR
      fonts:
        - asset: fonts/NotoSerifKR-Regular.otf

    - family: ONEMobileRegular
      fonts:
        - asset: fonts/ONE Mobile Regular.ttf

    - family: ONEMobileTitle
      fonts:
        - asset: fonts/ONE Mobile Title OTF.otf

    - family: ONEMobilePOP
      fonts:
        - asset: fonts/ONE Mobile POP OTF.otf
